                                        CREDIT RISK & LOAN DEFAULT ANALYSIS PROJECT
                                               Industry: Finance / BFSI

In [ ]:
# =============================================================================
# CREDIT RISK & LOAN DEFAULT ANALYSIS
# DATA ANALYST PROJECT
# =============================================================================

import pandas as pd
import numpy as np

# =============================================================================
# LOAD DATA
# =============================================================================

df = pd.read_csv("loan_default_dataset_1lakh.csv")


print("CREDIT RISK & LOAN DEFAULT ANALYSIS")


print("\nDataset Shape:", df.shape)

In [41]:
# DATA CLEANING
# =============================================================================

print("Dataset Shape:", df.shape)

# Remove duplicates
df = df.drop_duplicates()

# Handle missing values
df.fillna({
    "annual_income": df["annual_income"].median(),
    "credit_score": df["credit_score"].median(),
    "employment_type": "Unknown"
}, inplace=True)

Dataset Shape: (100000, 45)

In [51]:
# =============================================================================
# DATA QUALITY CHECKS
# =============================================================================
print("\nMISSING VALUES")
print(df.isnull().sum())


print("\nDUPLICATE RECORDS")
print(df.duplicated().sum())

MISSING VALUES
loan_id                0
application_date       0
application_year       0
application_month      0
application_quarter    0
application_channel    0
age                    0
gender                 0
marital_status         0
education              0
state                  0
city_tier              0
employment_type        0
emp_length_years       0
annual_income          0
monthly_income         0
loan_type              0
loan_purpose           0
loan_amount            0
loan_term_months       0
interest_rate          0
loan_grade             0
monthly_emi            0
collateral_value       0
ltv_ratio              0
co_applicant           0
credit_score           0
credit_history_yrs     0
num_open_accounts      0
num_credit_lines       0
credit_util_ratio      0
missed_payments        0
bankruptcies           0
derogatory_marks       0
home_ownership         0
has_vehicle            0
num_dependents         0
existing_loans         0
total_debt             0
debt_to_income         0
loan_to_income         0
emi_to_income          0
default_probability    0
loan_status            0
default                0
dtype: int64

DUPLICATE RECORDS
0

In [26]:
# =============================================================================
# PORTFOLIO KPI SUMMARY
# =============================================================================

portfolio_kpis = pd.DataFrame({

    "Metric":[
        "Total Loans",
        "Portfolio Value",
        "Average Loan Amount",
        "Average Credit Score",
        "Default Rate (%)",
        "Average Interest Rate (%)"
    ],

    "Value":[
        len(df),
        round(df["loan_amount"].sum(),0),
        round(df["loan_amount"].mean(),0),
        round(df["credit_score"].mean(),0),
        round(df["default"].mean()*100,2),
        round(df["interest_rate"].mean(),2)
    ]
})

print("\nPORTFOLIO KPI SUMMARY")

display(portfolio_kpis)

PORTFOLIO KPI SUMMARY

                      Metric         Value
0                Total Loans  1.000000e+05
1            Portfolio Value  3.530184e+10
2        Average Loan Amount  3.530180e+05
3       Average Credit Score  6.740000e+02
4           Default Rate (%)  2.313000e+01
5  Average Interest Rate (%)  1.673000e+01

In [27]:
# =============================================================================
# EXPLORATORY DATA ANALYSIS 

#LOAN GRADE ANALYSIS
# =============================================================================

loan_grade_analysis = (

    df.groupby("loan_grade")

    .agg(
        Applications=("loan_id","count"),
        Default_Rate=("default","mean"),
        Avg_Loan_Amount=("loan_amount","mean"),
        Avg_Credit_Score=("credit_score","mean")
    )

    .reset_index()
)

loan_grade_analysis["Default_Rate"] = (
    loan_grade_analysis["Default_Rate"]*100
).round(2)

print("\nLOAN GRADE ANALYSIS")
display(loan_grade_analysis)

LOAN GRADE ANALYSIS

  loan_grade  Applications  Default_Rate  Avg_Loan_Amount  Avg_Credit_Score
0          A         15094         22.98    348840.127733        674.438055
1          B         24896         22.90    350998.578687        674.286311
2          C         28014         23.50    357755.124366        674.925609
3          D         18152         23.16    354458.542144        673.952071
4          E          9800         23.27    351197.560714        674.013469
5          F          4044         21.98    346182.744065        673.551187

In [28]:
# =============================================================================
# EMPLOYMENT TYPE ANALYSIS
# =============================================================================

employment_analysis = (

    df.groupby("employment_type")

    .agg(
        Applications=("loan_id","count"),
        Default_Rate=("default","mean"),
        Avg_Income=("annual_income","mean")
    )

    .reset_index()
)

employment_analysis["Default_Rate"] = (
    employment_analysis["Default_Rate"]*100
).round(2)

print("\nEMPLOYMENT TYPE ANALYSIS")
display(employment_analysis)

EMPLOYMENT TYPE ANALYSIS

  employment_type  Applications  Default_Rate     Avg_Income
0  Business Owner         12973         22.19  125707.523318
1      Freelancer          7825         28.66   39565.121150
2      Government          7074         20.17   65184.170059
3        Salaried         50182         23.00   63068.128393
4   Self-Employed         21946         22.94   54501.427595

In [29]:
# LOAN PURPOSE ANALYSIS
# =============================================================================

purpose_analysis = (

    df.groupby("loan_purpose")

    .agg(
        Applications=("loan_id","count"),
        Default_Rate=("default","mean"),
        Avg_Loan=("loan_amount","mean")
    )

    .reset_index()
)

purpose_analysis["Default_Rate"] = (
    purpose_analysis["Default_Rate"]*100
).round(2)

print("\nLOAN PURPOSE ANALYSIS")
display(purpose_analysis)

LOAN PURPOSE ANALYSIS

         loan_purpose  Applications  Default_Rate       Avg_Loan
0  Business Expansion         11901         22.66  355036.026468
1  Debt Consolidation         20046         23.39  353609.058116
2           Education         10160         23.17  352398.798228
3       Home Purchase         18080         23.26  354291.737058
4     Home Renovation          8043         23.11  352917.842099
5   Medical Emergency          7962         22.95  351446.349535
6            Personal          6868         22.89  346411.380460
7    Vehicle Purchase         11974         23.25  352132.642392
8             Wedding          4966         22.96  356386.455900

In [30]:
# CREDIT SCORE BAND ANALYSIS
# =============================================================================

df["credit_band"] = pd.cut(

    df["credit_score"],

    bins=[300,550,650,750,850],

    labels=[
        "Poor",
        "Fair",
        "Good",
        "Excellent"
    ]
)

credit_band_analysis = (

    df.groupby("credit_band")

    .agg(
        Applications=("loan_id","count"),
        Default_Rate=("default","mean"),
        Avg_Loan=("loan_amount","mean")
    )

    .reset_index()
)
credit_band_analysis["Default_Rate"] = (
    credit_band_analysis["Default_Rate"]*100
).round(2)

print("\nCREDIT BAND ANALYSIS")
display(credit_band_analysis)

CREDIT BAND ANALYSIS

  credit_band  Applications  Default_Rate       Avg_Loan
0        Poor          7296         59.50  357804.917489
1        Fair         31451         27.89  352010.123367
2        Good         42648         19.39  353715.518078
3   Excellent         16697          9.77  350673.189974

In [32]:
# =============================================================================
# STATE LEVEL ANALYSIS
# =============================================================================

state_analysis = (

    df.groupby("state")

    .agg(
        Applications=("loan_id","count"),
        Default_Rate=("default","mean"),
        Avg_Loan=("loan_amount","mean"),
        Avg_Credit_Score=("credit_score","mean")
    )

    .reset_index()
)

state_analysis["Default_Rate"] = (
    state_analysis["Default_Rate"]*100
).round(2)

state_analysis = state_analysis.sort_values(
    by="Default_Rate",
    ascending=False
)

top_states = state_analysis.head(10)

print("\nTOP 10 STATES BY DEFAULT RATE")
display(top_states)

TOP 10 STATES BY DEFAULT RATE

,state,Applications,Default_Rate,Avg_Loan,Avg_Credit_Score
14,West Bengal,6657,23.78,352539.339042,673.342497
1,Bihar,6686,23.60,354649.934191,674.244690
10,Rajasthan,6620,23.56,348720.115559,675.346828
13,Uttar Pradesh,6705,23.56,355310.477852,674.907830
12,Telangana,6546,23.53,348642.551635,673.414146
11,Tamil Nadu,6650,23.38,352830.111729,672.968421
7,Madhya Pradesh,6764,23.27,356442.135866,674.499261
8,Maharashtra,6583,23.12,353483.443415,675.121525
5,Karnataka,6749,23.11,353213.754186,673.511780
6,Kerala,6636,23.01,359020.971670,674.987191

In [33]:
# DEBT TO INCOME ANALYSIS
# =============================================================================

df["DTI_Band"] = pd.qcut(
    df["debt_to_income"],
    5
)

dti_analysis = (

    df.groupby("DTI_Band")

    .agg(
        Applications=("loan_id","count"),
        Default_Rate=("default","mean")
    )

    .reset_index()
)

dti_analysis["Default_Rate"] = (
    dti_analysis["Default_Rate"]*100
).round(2)

print("\nDEBT TO INCOME ANALYSIS")
display(dti_analysis)

DEBT TO INCOME ANALYSIS

         DTI_Band  Applications  Default_Rate
0  (0.049, 0.279]         20042          9.25
1  (0.279, 0.508]         20033         13.89
2  (0.508, 0.736]         19944         30.83
3  (0.736, 0.967]         20058         31.25
4    (0.967, 1.2]         19923         30.48

In [34]:
# =============================================================================
# RISK TIER SEGMENTATION
# =============================================================================

df["Risk_Tier"] = pd.cut(

    df["credit_score"],

    bins=[300,550,650,750,850],

    labels=[
        "High Risk",
        "Medium Risk",
        "Low Risk",
        "Very Low Risk"
    ]
)

risk_tier_analysis = (

    df.groupby("Risk_Tier")

    .agg(
        Applications=("loan_id","count"),
        Default_Rate=("default","mean"),
        Avg_Loan=("loan_amount","mean"),
        Avg_Income=("annual_income","mean")
    )

    .reset_index()
)
risk_tier_analysis["Default_Rate"] = (
    risk_tier_analysis["Default_Rate"]*100
).round(2)

print("\nRISK TIER ANALYSIS")
display(risk_tier_analysis)

RISK TIER ANALYSIS

       Risk_Tier  Applications  Default_Rate       Avg_Loan    Avg_Income
0      High Risk          7296         59.50  357804.917489  67742.510828
1    Medium Risk         31451         27.89  352010.123367  67566.733268
2       Low Risk         42648         19.39  353715.518078  67746.029450
3  Very Low Risk         16697          9.77  350673.189974  67329.840271

In [37]:
high_risk_customers = (

    df[
        (df["credit_score"] < 600) &
        (df["debt_to_income"] > 0.75)
    ]

    .sort_values(
        by="loan_amount",
        ascending=False
    )

    .head(100)
)

print("\nHIGH RISK CUSTOMER ")
display(high_risk_customers.head())

HIGH RISK CUSTOMER

,loan_id,application_date,application_year,application_month,application_quarter,application_channel,age,gender,marital_status,education,...,total_debt,debt_to_income,loan_to_income,emi_to_income,default_probability,loan_status,default,credit_band,DTI_Band,Risk_Tier
31638,LN0031639,12/8/2023,2023,12,Q4,Online,49,Female,Married,Graduate,...,92041,1.125,5.0,3.0,0.6986,Fully Paid,0,Poor,"(0.967, 1.2]",High Risk
59621,LN0059622,5/27/2022,2022,5,Q2,Branch,65,Male,Married,Post Graduate,...,71233,0.910,5.0,3.0,0.3959,Default,1,Fair,"(0.736, 0.967]",Medium Risk
35887,LN0035888,12/30/2022,2022,12,Q4,Online,25,Male,Single,Doctorate,...,38766,0.798,5.0,3.0,0.5319,Charged Off,1,Fair,"(0.736, 0.967]",Medium Risk
39503,LN0039504,11/12/2024,2024,11,Q4,DSA,63,Female,Married,Graduate,...,19591,0.968,5.0,3.0,0.8008,Late (31-120 days),1,Poor,"(0.967, 1.2]",High Risk
24266,LN0024267,9/16/2024,2024,9,Q3,Branch,66,Female,Married,Graduate,...,6792,0.930,5.0,3.0,0.4315,Charged Off,1,Fair,"(0.736, 0.967]",Medium Risk

In [38]:
# EXPORT REPORT TO EXCEL
# =============================================================================

output_file = "Credit_Risk_Analysis_Report.xlsx"

with pd.ExcelWriter(output_file) as writer:

    portfolio_kpis.to_excel(
        writer,
        sheet_name="Portfolio KPI",
        index=False
    )

    loan_grade_analysis.to_excel(
        writer,
        sheet_name="Loan Grade",
        index=False
    )

    employment_analysis.to_excel(
        writer,
        sheet_name="Employment Type",
        index=False
    )

    purpose_analysis.to_excel(
        writer,
        sheet_name="Loan Purpose",
        index=False
    )

    credit_band_analysis.to_excel(
        writer,
        sheet_name="Credit Band",
        index=False
    )

    state_analysis.to_excel(
        writer,
        sheet_name="State Analysis",
        index=False
    )

    dti_analysis.to_excel(
        writer,
        sheet_name="DTI Analysis",
        index=False
    )

    risk_tier_analysis.to_excel(
        writer,
        sheet_name="Risk Tier",
        index=False
    )

    high_risk_customers.to_excel(
        writer,
        sheet_name="High Risk Customers",
        index=False
    )

print("\n" + "="*70)
print("REPORT GENERATED SUCCESSFULLY")
display("Output File : Credit_Risk_Analysis_Report.xlsx")
print("="*70)

======================================================================
REPORT GENERATED SUCCESSFULLY

'Output File : Credit_Risk_Analysis_Report.xlsx'

======================================================================